
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbtlearn'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbtlearn'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

#This are hooks which run when we run any dbt run/compile/test and performs some task(here creating
# a audit table)
on-run-start:
  - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log (
      model_name STRING,
      run_timestamp TIMESTAMP
    )"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbtlearn:
    +grants:
      select: ["transform", "reporter"]
#This a new way of granting permissions rather than using hooks

    +post-hooks:
      - "Grant Select on {{this}} to role Reporter"
    #This will grant Select permisiion of a model when it's build to Reporter. 
      - "INSERT INTO {{ target.schema }}.audit_log VALUES ('{{ this }}', CURRENT_TIMESTAMP)"
    +materialized: view # By Default any src or dim or fact table create will be a view
    
    #This will insert into the audit table values after each model is build.
    dim:
      +materialized: table #Only Tables create in dim folder will be tables.
    src:
      +materialized: ephemeral #This setting makes the table created temporary and are not stored in
      #the DW, this sql files will be executed every time we 'dbt run' and since DW doesnot have the 
      #table it cannot access the data in it directly. #We can see the result of running them in tgt folder
vars:
  user_name: This is value declared in dbt_project

  data_tests:
  +store_failures: true
  +schema: _test_failures
#if we want to store failures while testing, in the database we have to enable this setting.